### ISSUE TITLE
8735! nightmare corruption

### ISSUE THREAD

**Issue by rmzV** [cmangos/wotlk-db#70] opened 2017-01-30 18:35 UTC
http://wowwiki.wikia.com/wiki/Quest:The_Nightmare%27s_Corruption
dragons does not drop fragments 
and 4 fragment must be dropped of 
http://wowwiki.wikia.com/wiki/Twilight_Corrupter

**Comment by rmzV** [comment] 2017-02-09 06:16
Grz3s , where is the Corrupter NPC, i killed dragon in Duskwood come to moonwell in back and nothing

**Comment by Grz3s** [comment] 2017-02-09 20:40
ops ..you're right ...
ill look again on this one...

**Comment by evil-at-wow** [comment] 2017-02-10 19:55
The world dragon shouldn't even be there if you're on the quest. That could be tricky to do with the current core. I don't know how it was actually done, but the effect you saw was as if you were in a different phase. Maybe it was actually that way in WoTLK, but I don't know how they did it back in TBC and Classic (no phasing I think?).

**Comment by Grz3s** [comment] 2017-02-10 20:39
100% not phases...  I saw ppl kiting this Boss into Stormwind... (not in party)... so how they all could see him?
BTW:
I've never seen  in pre cata ... that older quests with working scripts .. were redone .. using newer method (phases were added in wotlk)

It must be a trigger  (invis npc)... that starts event if player has correct quest "on"...
- despawn dragon
- summon Corrupter

This comment:
> If he despawns, or if you need to kill him again for other people, just go up the ramp and out of the dragon area until you see a whisper from him in your chat log. Once you see that, he's respawned and can be killed again.

This means for me... that invis npc must be there... and reacts on LOS with conditios)

**Comment by rmzV** [comment] 2017-02-10 20:45
yep.. bact in tbc live, we just come and kill npc for q -item. so no phasing

**Comment by cala** [comment] 2017-09-20 09:23
> This means for me... that invis npc must be there... and reacts on LOS with conditions)

I'm pretty sure there is an areatrigger right before entering the mountain circle where the Emerald Dragon and Corruptor are located. That means we probably need SD2 support here, but I agree with @evil-at-wow : the way the four dragons are handled in core now is troublesome for this event. We need to be able to share data about them worldwide (across map 0 and map 1).

**Comment by killerwife** [comment] 2017-09-20 09:30
Ehhh, are you sure? because i have a system that enables it, but its a rough prototype for some TBC/zeppelin stuff. What exactly needs to be done cross map?

**Comment by cala** [comment] 2017-09-20 10:12
To be more accurate: currently the four Emerald Dragons are handled like static spawns and this is wrong.
Keeping the static spawn approach we could easily hard code to (temporary) remove the correct dragon (this is Taerar at the moment) once the areatrigger is triggered and spawn the Corruptor instead.

But if we want to correctly spawn the Dragons, we need to randomize them across 4 places located on two different maps and keep track of them to handle the respawn with the correct entry (and possibly the despawn in TBC or WotLK branch as this was handled by server reboot/maintenance in Classic times). Then, for the Corruptor script, we need to either have access to the entry of the Dragon currently spawned in the place where the event is supposed to happen or search for the 4 Dragons (and hope to find one) and despawn it.

**Comment by killerwife** [comment] 2017-09-20 10:29
What? There are 4 dream locations, duskwood, feralas, hinterlands and ashenvale. Each one should contain exactly one specific dragon with WPs or not? Or are those spawns shared for all the dragons across all the 4 zones?

**Comment by cala** [comment] 2017-09-20 11:28
> Or are those spawns shared for all the dragons across all the 4 zones?

In retail, they are (were). In CMaNGOS they are not.

**Comment by killerwife** [comment] 2017-09-20 11:33
so you need a global manager for spawning dragons which you will be able to query in the corruptor script?

**Comment by cala** [comment] 2017-09-20 11:48
Yes. :-)

**Comment by rmzV** [comment] 2017-09-21 16:52
guys.. i am a bit lost
if recall it right:this, was how it was working on live:
"here are 4 dream locations, duskwood, feralas, hinterlands and ashenvale. Each one should contain exactly one specific dragon"

what you mean by:"those spawns shared for all the dragons across all the 4 zones" dragons are random? or?

**Comment by evil-at-wow** [comment] 2017-09-21 20:42
@rmzV There was not a one to one mapping between the four locations and the four dragons, or in other words a particular dragon did not spawn in a fixed location, but at random in one of the four possible locations. So if you wanted to see for example Emeriss,  you could perhaps find him Duskwood today, but in Feralas after a server reboot. That's what killerwife meant with 'shared spawns'.

And maybe you can just search for any of the four dragons in a large enough range or part of the grid or so... no ideal, but probably doable.

@cala You're talking about removing the correct dragon and so. But do you happen to know if that actually was always the case back in the days? I've done that quest myself during WoTLK, so I can confirm that the world dragon was replaced by the Corrupter for me when I first went for a kill, and once more later when I was going to kill him with a friend in a party/raid (I don't remember), but that was at a time when Duskwood was like completely deserted on my realm so it was a rather trivial situation to handle.

Now imagine a raid group pulling the world dragon in Duskwood, and half way through their fight this little warlock, having the Corrupter's quest available, is entering the Twilight Grove on his Dreadsteed... now what? Do I see a raid fighting a world dragon? I can't imagine I'd wreck their attempt by having the world dragon (temporarily) despawn! That would also imply I could make them wait forever whoehaha, because I could be staying there for hours! And what if they wipe? A quick respawn of the world dragon (assuming it doesn't "return home" but uses the now common despawn/respawn)? Again, I can't imagine I control whether they will get another attempt today. And do I see my Corrupter? Or not? If I do, do they see it too? Etc.

All questions we'll probably never be able to answer for sure, but I'm sure you understand why I said this could be tricky :smile:

**Comment by cala** [comment] 2017-09-22 15:48
> You're talking about removing the correct dragon and so. But do you happen to know if that actually was always the case back in the days?

@evil-at-wow I don't. I should have known as my guild was the one that opened the Gates of Ahn'Qiraj on the server I was playing on, unfortunately, I was not available the day we did the Twilight Corruptor encounter.

Thus, I was taking your comment:
> The world dragon shouldn't even be there if you're on the quest. 

as an adamant version of how it should be, and then was thinking about ways to do it on CMaNGOS (without giving a thought to side effects for now).

But if you are asking for my personal opinion, I think it is quite possible that the Twilight Corruptor spawn is completely unrelated to the presence or absence of a nearby dragon and that "the dragon is not here" is probably a consequence of their extremely short life expectancy. Hence, a raid can quite possible to have to clear the nearby dragon before engaging the corruptor (there is enough distance between the two spawn positions to avoid a double pull if being careful).

**Comment by cala** [comment] 2017-09-22 15:53
By the way, [this](http://www.wowhead.com/npc=15625/twilight-corrupter#comments:id=432710) confirms that this is done by an areatrigger located at the grove entrance.

**Comment by rmzV** [comment] 2019-02-01 19:48
https://github.com/cmangos/classic-db/commit/bed3e9f9af5fc07d4684742ed1d2f3b2188cb62e
https://github.com/cmangos/tbc-db/commit/4449a5bfd1f40ba391169ce03ed89d40b9767d5b

maybe it helps

**Comment by cala** [comment] 2019-02-19 14:39
@rmzV I'm aware of these changes, as you might guess but they are unrelated.
However, I've started working on this issue.

**Comment by cala** [comment] 2019-02-27 12:54
Closed by https://github.com/cmangos/mangos-wotlk/commit/e43e5b555959cb690a56f97f01419dd88417265a and https://github.com/cmangos/wotlk-db/commit/355de0f698df16743d1220236e0e91a09d19afee

**Closed by cala** 2019-02-27 12:54 UTC
Labels: Core / Scriptdev2, Npc, Quest

**Comment by rmzV** [comment] 2019-03-10 08:19
twillight corrupter for some reason friendly unit

can you please also look at blue fork of this quest chain

**Comment by NeatElves** [comment] 2019-03-10 08:44
```sql
UPDATE `creature_template` SET `Faction` = '14' WHERE `Entry` =15625;
```

**Comment by rmzV** [comment] 2019-03-14 18:28
still no ingame fix? do we need to repen case? if so ->how to do it?(

**Comment by AnonXS** [comment] 2019-03-15 08:20
wotlk-db is probably just  missing backports from classic-db

**Comment by Grz3s** [comment] 2019-03-19 21:03
just in case... :)... 
before i'll forget ....

**Comment by AnonXS** [comment] 2019-03-19 21:07
noted in spreadsheet +1

**Comment by al3xc1985** [comment] 2019-03-19 21:24
just in case 2 for @Grz3s , the same thing with tbc backports ;P from a long time ago :+1:

**Comment by AnonXS** [comment] 2019-03-19 21:42
https://docs.google.com/spreadsheets/d/1wUqlVgPWy2b0x9_hFK_b5ImDMeAxmizPuT4J7t9xQFQ/edit#gid=1619028247

**Comment by Grz3s** [comment] 2019-03-19 22:12
@al3xc1985 well yes... but In the meantime i also ReDid whole Howling Fjord (including all quests for both sides, all events, waypoints spawns etc etc... ) .. You can ask any dbdev.. what kind of work this is :)... I wanted to backport everything from TBCDB  up to 1.7.0 and thats done. (+ much more from @AnonXS for acid) ... 
We've got 1848 commits since last Release... and all i need is to add last "thing" im working on* (it will take some time) and I'm ready for wrapping up new Release...

**Comment by rmzV** [comment] 2019-03-20 17:27
@Grz3s , thank you for your work

i understand it right vanillaDb ported to TBCDb and then TBCDb ported to WotlkDb?
what does this spreadsheets for?
can i look at?

**Comment by AnonXS** [comment] 2019-03-20 19:03
its just for wotlk cherrypicking commits from either classic or tbc-db, the commits should always be cherrypicked from the repo the fix was originally first commited to, but anyways, no real need to look at it as its only worth for people to look at if they can also help with maintaining syncro between repos.

**Comment by al3xc1985** [comment] 2019-03-20 19:33
@Grz3s I am very patience, and I appreciate very much your work! My remark was just a joke. I even made a private server for my self to test everything you do, as a respect of everything you've done, and do. 

Respect, and wait to see more from you!

P.S. Sorry for the offtopic, I didn't wanted to be missunderstoud

**Comment by rmzV** [comment] 2019-03-21 17:00
@AnonXS , okey.. its top secret:)

just was woundered..if i can check vanilla and tbcs fixes for my personal check list.. //you know i trying to make somethink like a full test and need some old quest to be fixed//

**Comment by AnonXS** [comment] 2019-03-21 17:46
if data aligns, its not tested for the most part, if it needs expansion related changes, then yes, as otherwise it is taken for granted that due to scripts and relations being the same across cores, that stuff works with the same db data in place.

**Comment by Grz3s** [comment] 2019-03-21 19:02
Its not always that easy....
- if texts are involved .. 100% ids are diff...
- if guids for creatures/objects are used .. very ofter they will be diff also.
- Using DBScripts or ACID... for changing unitflags... you'll also find diffs
example:
```code
UNIT_FIELD_FLAGS - (59-wotlk) (46-tbc)
UNIT_NPC_FLAGS   - (82-wotlk) (168-tbc)
```
